"""add: car

Revision ID: ab496cdbf2da
Revises: 074768d3fb72
Create Date: 2025-06-11 15:52:18.980239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab496cdbf2da'
down_revision: Union[str, None] = '074768d3fb72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('published_year', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('password', sa.String(length=50), nullable=False))
    op.drop_column('users', 'passeord')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passeord', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('users', 'password')
    op.drop_table('cars')
    # ### end Alembic commands ###
